export const SAMPLE_ORIGIN = {
  address: '77 Massachusetts Ave, Cambridge, MA 02139, United States',
  lat: 42.3594,
  lng: -71.0938,
};

export const SAMPLE_LISTINGS = [
  {
    id: 'L1',
    agent: 'Sarah Chen',
    address: '123 Massachusetts Ave, Cambridge, MA 02139',
    type: 'Studio',
    price: 1950,
    priceMax: 2100,
    includesUtilities: false,
    amenities: ['Laundry in building', 'Bike storage', 'Hardwood floors'],
    pros: ['5 min walk to MIT', 'Quiet street', 'Natural light'],
    cons: ['Small kitchen', 'No dishwasher'],
    moveInDate: '2026-09-01',
    description: 'Cozy studio steps from campus, recently renovated bathroom.',
    lat: 42.3650, lng: -71.1031,
    distance: 1.0,
    commute: { walking: 13, transit: 8, driving: 5 },
    status: 'done', geocodeError: false,
    resolvedAddress: '123 Massachusetts Ave, Cambridge, Middlesex County, Massachusetts, United States',
  },
  {
    id: 'L2',
    agent: 'Mike Johnson',
    address: '45 Roseland St, Somerville, MA 02143',
    type: '1B1B',
    price: 2400,
    priceMax: 2600,
    includesUtilities: false,
    amenities: ['In-unit W/D', 'Parking', 'Private deck'],
    pros: ['Porter Square T nearby', 'Spacious layout', 'Pet friendly'],
    cons: ['30 min commute', 'Older building'],
    moveInDate: '2026-08-15',
    description: 'Bright 1BR with private deck in quiet Somerville neighborhood.',
    lat: 42.3884, lng: -71.1190,
    distance: 3.9,
    commute: { walking: 52, transit: 20, driving: 12 },
    status: 'done', geocodeError: false,
    resolvedAddress: '45 Roseland St, Somerville, Middlesex County, Massachusetts, United States',
  },
  {
    id: 'L3',
    agent: 'Sarah Chen',
    address: '87 Hampshire St, Cambridge, MA 02139',
    type: '1B1B',
    price: 2200,
    priceMax: null,
    includesUtilities: true,
    amenities: ['Gym', 'Rooftop deck', 'Concierge', 'Package room'],
    pros: ['Utilities included', 'Modern building', 'Inman Square vibe'],
    cons: ['Higher price', 'Busy street'],
    moveInDate: 'ASAP',
    description: 'Modern 1BR in boutique building with rooftop access. All utilities included.',
    lat: 42.3732, lng: -71.1014,
    distance: 1.7,
    commute: { walking: 22, transit: 12, driving: 7 },
    status: 'done', geocodeError: false,
    resolvedAddress: '87 Hampshire St, Cambridge, Middlesex County, Massachusetts, United States',
  },
  {
    id: 'L4',
    agent: 'David Park',
    address: '200 Commonwealth Ave, Boston, MA 02116',
    type: '2B2B',
    price: 3800,
    priceMax: 4200,
    includesUtilities: false,
    amenities: ['Doorman', 'Elevator', 'Gym', 'Garage parking'],
    pros: ['Back Bay location', 'Beautiful brownstone block', 'High-end finishes'],
    cons: ['Expensive', 'Parking extra $300/mo', 'Farther from MIT'],
    moveInDate: '2026-09-01',
    description: 'Classic Back Bay 2BR in a well-maintained brownstone, great for two roommates.',
    lat: 42.3519, lng: -71.0821,
    distance: 1.3,
    commute: { walking: 17, transit: 15, driving: 8 },
    status: 'done', geocodeError: false,
    resolvedAddress: '200 Commonwealth Ave, Boston, Suffolk County, Massachusetts, United States',
  },
  {
    id: 'L5',
    agent: 'Mike Johnson',
    address: '312 Harvard Ave, Allston, MA 02134',
    type: '2B1B',
    price: 2700,
    priceMax: 2900,
    includesUtilities: false,
    amenities: ['In-unit W/D', 'Backyard', 'Storage unit'],
    pros: ['Large rooms', 'Backyard', 'Good for roommates'],
    cons: ['Further from campus', 'Street parking only', 'Noisy on weekends'],
    moveInDate: '2026-09-01',
    description: 'Spacious 2BR with backyard in lively Allston. Great for grad students.',
    lat: 42.3534, lng: -71.1269,
    distance: 2.9,
    commute: { walking: 39, transit: 18, driving: 10 },
    status: 'done', geocodeError: false,
    resolvedAddress: '312 Harvard Ave, Allston, Suffolk County, Massachusetts, United States',
  },
  {
    id: 'L6',
    agent: 'Lisa Wang',
    address: '15 College Ave, Somerville, MA 02144',
    type: 'Studio',
    price: 1850,
    priceMax: 2050,
    includesUtilities: false,
    amenities: ['Laundry in building', 'Bike room', 'Cat friendly'],
    pros: ['Davis Square restaurants nearby', 'Affordable', 'Quiet neighborhood'],
    cons: ['Longer commute', 'Small unit', 'No A/C'],
    moveInDate: '2026-08-01',
    description: 'Charming studio near Davis Square. Great restaurants and coffee shops downstairs.',
    lat: 42.3963, lng: -71.1225,
    distance: 4.8,
    commute: { walking: 64, transit: 22, driving: 15 },
    status: 'done', geocodeError: false,
    resolvedAddress: '15 College Ave, Somerville, Middlesex County, Massachusetts, United States',
  },
  {
    id: 'L7',
    agent: 'David Park',
    address: '55 Burbank St, Boston, MA 02115',
    type: '1B1B',
    price: 2600,
    priceMax: null,
    includesUtilities: false,
    amenities: ['Gym', 'Roof deck', 'Virtual doorman'],
    pros: ['Fenway Park views', 'Modern appliances', 'Near Green Line'],
    cons: ['Game day noise', 'Limited storage'],
    moveInDate: '2026-07-15',
    description: 'Sleek 1BR in Fenway with roof deck and city views. Near major hospitals.',
    lat: 42.3448, lng: -71.0934,
    distance: 1.6,
    commute: { walking: 21, transit: 14, driving: 8 },
    status: 'done', geocodeError: false,
    resolvedAddress: '55 Burbank St, Boston, Suffolk County, Massachusetts, United States',
  },
  {
    id: 'L8',
    agent: 'Lisa Wang',
    address: '237 Main St, Cambridge, MA 02142',
    type: 'Studio',
    price: 2300,
    priceMax: null,
    includesUtilities: true,
    amenities: ['Concierge', 'Gym', 'Bike share', 'Rooftop'],
    pros: ['Closest to MIT', 'All utilities included', 'Brand new building'],
    cons: ['Expensive for studio', 'Less character'],
    moveInDate: 'ASAP',
    description: 'Brand new luxury studio in Kendall Square. Walking distance to MIT and tech companies.',
    lat: 42.3624, lng: -71.0862,
    distance: 0.7,
    commute: { walking: 9, transit: 6, driving: 4 },
    status: 'done', geocodeError: false,
    resolvedAddress: '237 Main St, Cambridge, Middlesex County, Massachusetts, United States',
  },
];
